meta_product_name: "Contribution Carbone"
meta_title: "Contribution Carbone - Créons le cahier des charges citoyen de la compensation carbone "
meta_description: "Marre du Greenwashing? Aidez-nous à construire le 1er cahier des charges des consommateurs-citoyens de la compensation carbone !"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"